# This file is a template, and might need editing before it works on your project.
# Official docker image.

build:
  stage: build
  tags:
    - shell-runner
  script:
    - Temp
    # - echo $CI_BUILD_REF_NAME
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ii.org.nz
    # - docker build -t docker.ii.org.nz/$CI_PROJECT_NAMESPACE/handbook:$CI_BUILD_REF_NAME .
    # - docker push docker.ii.org.nz/$CI_PROJECT_NAMESPACE/handbook:$CI_BUILD_REF_NAME
